import 'package:flutter/material.dart';
import 'package:flutterapp/maplifeapp/generatedsplashwidget/generated/GeneratedButtonWidget2.dart';
import 'package:flutterapp/maplifeapp/generatedsplashwidget/generated/GeneratedMaplifeicon1Widget.dart';
import 'package:flutterapp/maplifeapp/generatedsplashwidget/generated/GeneratedButtonWidget.dart';

/* Frame Splash
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 412.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -8.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 427.0,
                child: GeneratedMaplifeicon1Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 708.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 64.0,
                child: GeneratedButtonWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 628.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 64.0,
                child: GeneratedButtonWidget2(),
              )
            ]),
      ),
    ));
  }
}
