import 'package:flutter/material.dart';
import 'package:flutterapp/maplifeapp/generatedmapwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/maplifeapp/generatedmapwidget/generated/GeneratedMAPLIFEWidget.dart';
import 'package:flutterapp/maplifeapp/generatedmapwidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/maplifeapp/generatedmapwidget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/maplifeapp/generatedmapwidget/generated/GeneratedNavWidget.dart';
import 'package:flutterapp/maplifeapp/generatedmapwidget/generated/GeneratedMenuWidget.dart';
import 'package:flutterapp/maplifeapp/generatedmapwidget/generated/GeneratedNotificationsWidget.dart';
import 'package:flutterapp/maplifeapp/generatedmapwidget/generated/GeneratedSettingsWidget.dart';

/* Frame Map
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMapWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 412.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 133.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 15.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 61.123077392578125,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6601941747572816;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17475728155339806,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedMAPLIFEWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 79.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 42.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 89.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedSearchWidget(),
              ),
              Positioned(
                left: 327.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNotificationsWidget(),
              ),
              Positioned(
                left: 363.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMenuWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedSettingsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 93.0,
                child: GeneratedNavWidget(),
              )
            ]),
      ),
    ));
  }
}
