import 'package:flutter/material.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedNavWidget1.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedAnyStreetWidget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedEmailAddressWidget1.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedWeightlbsWidget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/Generated140Widget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedStreetAddressWidget1.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedPhoneNumberWidget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedProfile11Widget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/Generated57Widget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/Generated28Widget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedEmailemailcomWidget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedAgeWidget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedEDITSAFETYNETWidget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedAnytownNTUSA10000Widget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/Generated15555555555Widget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedHeightWidget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedProfileWidget2.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedEditWidget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilewidget1/generated/GeneratedFirstNameLastNameWidget.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 412.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 451.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 75.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 66.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 285.0,
                height: 63.0,
                child: GeneratedProfileWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 212.0,
                child: GeneratedProfile11Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 478.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 93.0,
                child: GeneratedNavWidget1(),
              ),
              Positioned(
                left: 32.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 35.0,
                child: GeneratedFirstNameLastNameWidget(),
              ),
              Positioned(
                left: 348.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedEditWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 32.0,
                child: GeneratedEmailAddressWidget1(),
              ),
              Positioned(
                left: 48.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 64.0,
                child: GeneratedEmailemailcomWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 32.0,
                child: GeneratedPhoneNumberWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 35.0,
                child: GeneratedAgeWidget(),
              ),
              Positioned(
                left: 182.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 35.0,
                child: GeneratedHeightWidget(),
              ),
              Positioned(
                left: 297.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 32.0,
                child: GeneratedWeightlbsWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 64.0,
                child: Generated15555555555Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 64.0,
                child: Generated28Widget(),
              ),
              Positioned(
                left: 175.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 64.0,
                child: Generated57Widget(),
              ),
              Positioned(
                left: 297.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 64.0,
                child: Generated140Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 32.0,
                child: GeneratedStreetAddressWidget1(),
              ),
              Positioned(
                left: 48.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 61.0,
                child: GeneratedAnyStreetWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 61.0,
                child: GeneratedAnytownNTUSA10000Widget(),
              ),
              Positioned(
                left: 75.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 35.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 23.0,
                child: GeneratedEDITSAFETYNETWidget(),
              )
            ]),
      ),
    ));
  }
}
