import 'package:flutter/material.dart';
import 'package:flutterapp/maplifeapp/generatedprofilecreatewidget/generated/GeneratedSignUpFieldWidget5.dart';
import 'package:flutterapp/maplifeapp/generatedprofilecreatewidget/generated/GeneratedProfilePicAddWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/maplifeapp/generatedprofilecreatewidget/generated/GeneratedSignUpWidget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilecreatewidget/generated/GeneratedSignUpFieldWidget7.dart';
import 'package:flutterapp/maplifeapp/generatedprofilecreatewidget/generated/GeneratedSignUpFieldWidget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilecreatewidget/generated/GeneratedSignUpFieldWidget2.dart';
import 'package:flutterapp/maplifeapp/generatedprofilecreatewidget/generated/GeneratedButtonWidget14.dart';
import 'package:flutterapp/maplifeapp/generatedprofilecreatewidget/generated/GeneratedSignUpFieldWidget1.dart';
import 'package:flutterapp/maplifeapp/generatedprofilecreatewidget/generated/GeneratedSignUpFieldWidget3.dart';
import 'package:flutterapp/maplifeapp/generatedprofilecreatewidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/maplifeapp/generatedprofilecreatewidget/generated/GeneratedSignUpFieldWidget4.dart';

/* Frame ProfileCreate
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileCreateWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 412.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 75.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 10.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 58.123077392578125,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6529126213592233;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17475728155339806,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedSignUpWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 146.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 119.0,
                child: GeneratedProfilePicAddWidget(),
              ),
              Positioned(
                left: 60.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 40.0,
                child: GeneratedSignUpFieldWidget(),
              ),
              Positioned(
                left: 60.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 40.0,
                child: GeneratedSignUpFieldWidget1(),
              ),
              Positioned(
                left: 60.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 40.0,
                child: GeneratedSignUpFieldWidget2(),
              ),
              Positioned(
                left: 60.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 40.0,
                child: GeneratedSignUpFieldWidget3(),
              ),
              Positioned(
                left: 60.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 40.0,
                child: GeneratedSignUpFieldWidget4(),
              ),
              Positioned(
                left: 60.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 90.0,
                child: GeneratedSignUpFieldWidget5(),
              ),
              Positioned(
                left: 49.0,
                top: 708.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 64.0,
                child: GeneratedButtonWidget14(),
              ),
              Positioned(
                left: 60.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 40.0,
                child: GeneratedSignUpFieldWidget7(),
              )
            ]),
      ),
    ));
  }
}
